<a href="https://colab.research.google.com/github/irravasyuk/SQL_2/blob/master/practice_13_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [4]:
array = np.arange(1, 13)
print("Розмір масиву: ", array.shape)
print("Тип масиву: ", type(array))

Розмір масиву:  (12,)
Тип масиву:  <class 'numpy.ndarray'>


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [10]:
matrix = array.reshape((3, 4))
matrix = matrix.astype(np.float32)
tr_matrix = matrix.T

print("Матриця: ")
print(matrix)

print("Тип даних:", matrix.dtype)
print("Транспонована матриця:")
print(tr_matrix)

Матриця: 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Тип даних: float32
Транспонована матриця:
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [15]:
chessboard = np.indices((8, 8)).sum(axis=0)%2

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [13]:
random_matrix = np.random.rand(4, 3)
print("Випадкова матриця:")
print(random_matrix)

sum_columns = np.sum(random_matrix, axis = 0)
print("Сума елементів у стовпчиках:")
print(sum_columns)

sum_rows = np.sum(random_matrix, axis = 1)
print("Сума елементів у рядках:")
print(sum_rows)

sum_total = np.sum(random_matrix)
print("Сума всіх елементів матриці:")
print(sum_total)





Випадкова матриця:
[[0.09190873 0.23858288 0.21928339]
 [0.47386482 0.40536849 0.3798635 ]
 [0.11283296 0.61941182 0.17319699]
 [0.91727808 0.05114373 0.21046546]]
Сума елементів у стовпчиках:
[1.59588459 1.31450692 0.98280935]
Сума елементів у рядках:
[0.54977501 1.25909682 0.90544177 1.17888726]
Сума всіх елементів матриці:
3.8932008627193335


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [14]:
random_matrix = np.random.rand(4, 3)
print("Випадкова матриця:")
print(random_matrix)

max_in_rows = np.max(random_matrix, axis = 1).reshape(-1, 1)
result = random_matrix - max_in_rows

print("Матриця:")
print(result)

Випадкова матриця:
[[0.04420942 0.49697873 0.62172225]
 [0.11358817 0.73621449 0.90983658]
 [0.77076293 0.49751047 0.72170901]
 [0.08986483 0.32818627 0.6562935 ]]
Матриця:
[[-0.57751283 -0.12474352  0.        ]
 [-0.79624841 -0.1736221   0.        ]
 [ 0.         -0.27325246 -0.04905392]
 [-0.56642867 -0.32810724  0.        ]]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.