<a href="https://colab.research.google.com/github/irravasyuk/SQL_2/blob/master/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [2]:
even_num = np.arange(30, 71, 2)
print("Масив з парними числами між 30 і 70:\n", even_num)

Масив з парними числами між 30 і 70:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [3]:
array = np.linspace(0, 1, num = 11, endpoint=False)
print(array)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [4]:
def matrix_zero(matrix):
  n = matrix.shape[0]

  new_matrix = np.zeros((n + 2, n + 2), dtype=matrix.dtype)

  new_matrix[1:n+1, 1:n+1] = matrix

  return new_matrix

input_matrix = np.array([[1,2], [3,4]])
output_matrix = matrix_zero(input_matrix)

print(output_matrix)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [6]:
def matrix_zero(matrix):
  n = matrix.shape[0]

  new_matrix = np.zeros((n + 2, n + 2), dtype=matrix.dtype)

  new_matrix[1:n+1, 1:n+1] = matrix

  return new_matrix

input_matrix = np.array([[1,2], [3,4]])
output_matrix = matrix_zero(input_matrix)

print(output_matrix)

print("Тип даних до зміни:\n", output_matrix.dtype)

changed_type = output_matrix.astype(np.float16)

print("Тип даних після зміни:\n", changed_type.dtype)
print(changed_type)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]
Тип даних до зміни:
 int64
Тип даних після зміни:
 float16
[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [3]:
import numpy as np
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

x[x < var] = -1
x[x > var] = -1

print(x)

[-1  5 -1 -1 -1  5 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [4]:
import numpy as np
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

mask = np.isnan(X)

X[mask] = -1

print(X)


[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [5]:
import numpy as np

matrix_4x6 = np.random.random((4, 6))
print("Матриця 4x6")
print(matrix_4x6)
print("Розмір матриці:", matrix_4x6.shape)

matrix_3x8 = matrix_4x6.reshape(3, 8)

print("Матриця 3x8")
print(matrix_3x8)
print("Розмір матриці:", matrix_3x8.shape)


Матриця 4x6
[[0.63633947 0.46190581 0.12164659 0.6110616  0.48223859 0.05863074]
 [0.46626054 0.58446264 0.35629436 0.79798493 0.20483647 0.22328218]
 [0.48392048 0.94325325 0.47899706 0.59408204 0.12994507 0.23811432]
 [0.0679227  0.55928837 0.68220927 0.01430506 0.06958022 0.24587664]]
Розмір матриці: (4, 6)
Матриця 3x8
[[0.63633947 0.46190581 0.12164659 0.6110616  0.48223859 0.05863074
  0.46626054 0.58446264]
 [0.35629436 0.79798493 0.20483647 0.22328218 0.48392048 0.94325325
  0.47899706 0.59408204]
 [0.12994507 0.23811432 0.0679227  0.55928837 0.68220927 0.01430506
  0.06958022 0.24587664]]
Розмір матриці: (3, 8)


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [7]:
import numpy as np

matrix = np.ones((3, 4))

print("Матриця:\n", matrix)

arithmetic_mean = np.mean(matrix, axis = 0)
print("Середнє арифметичне стовпчиків:", arithmetic_mean)

Матриця:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Середнє арифметичне стовпчиків: [1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [9]:
import numpy as np

matrix = np.random.random((5, 6))

print("Матриця випадкових чисел:")
print(matrix)

rounded_matrix = np.round(matrix, decimals=1)

print("\nОкруглена таблиця:")
print(rounded_matrix)

sorted_first_row = np.sort(rounded_matrix[0])
sorted_matrix = np.array([sorted_first_row] + [row for row in rounded_matrix[1:]])

print("Відсортована матриця: ")
print(sorted_matrix)

Матриця випадкових чисел:
[[0.97571353 0.46234548 0.67920558 0.94084561 0.73999079 0.10108438]
 [0.60245477 0.34343813 0.07645744 0.72397313 0.75219986 0.89403167]
 [0.51404682 0.29449677 0.0174791  0.93057711 0.75556498 0.91859694]
 [0.70408882 0.86370737 0.81339831 0.03495786 0.54473596 0.69901898]
 [0.05625928 0.02882429 0.99285216 0.34173807 0.47343109 0.82221771]]

Округлена таблиця:
[[1.  0.5 0.7 0.9 0.7 0.1]
 [0.6 0.3 0.1 0.7 0.8 0.9]
 [0.5 0.3 0.  0.9 0.8 0.9]
 [0.7 0.9 0.8 0.  0.5 0.7]
 [0.1 0.  1.  0.3 0.5 0.8]]
Відсортована матриця: 
[[0.1 0.5 0.7 0.7 0.9 1. ]
 [0.6 0.3 0.1 0.7 0.8 0.9]
 [0.5 0.3 0.  0.9 0.8 0.9]
 [0.7 0.9 0.8 0.  0.5 0.7]
 [0.1 0.  1.  0.3 0.5 0.8]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [10]:
import numpy as np
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

elements = np.logical_and(X >= 3, X <= 6)

result = X[elements]

print("Елементи між 3 і 6:")
print(result)

Елементи між 3 і 6:
[3 4 5 6 6 5 4 3]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [13]:
import numpy as np

matrix = np.random.random((5, 6))

print("Матриця випадкових чисел:")
print(matrix)

normalized_row = (matrix - matrix.min(axis=0)) / (matrix.max(axis=0) - matrix.min(axis=0))
print("\nНормалізована матриця:")
print(normalized_row)

Матриця випадкових чисел:
[[0.22036808 0.2641169  0.62217727 0.56372444 0.08887763 0.46164054]
 [0.36955263 0.04973786 0.05726703 0.29841326 0.08948384 0.33082654]
 [0.88370031 0.84389837 0.44837916 0.79864316 0.13577463 0.85863843]
 [0.32362428 0.05405895 0.67849562 0.06982688 0.21340491 0.61837877]
 [0.00816363 0.66393559 0.01935016 0.78050216 0.77413338 0.97575489]]

Нормалізована матриця:
[[2.42370718e-01 2.69944212e-01 9.14558539e-01 6.77670870e-01
  0.00000000e+00 2.02834946e-01]
 [4.12762837e-01 0.00000000e+00 5.75242902e-02 3.13640604e-01
  8.84654529e-04 0.00000000e+00]
 [1.00000000e+00 1.00000000e+00 6.50886691e-01 1.00000000e+00
  6.84372184e-02 8.18403917e-01]
 [3.60305466e-01 5.44107359e-03 1.00000000e+00 0.00000000e+00
  1.81723803e-01 4.45866948e-01]
 [0.00000000e+00 7.73392434e-01 0.00000000e+00 9.75108951e-01
  1.00000000e+00 1.00000000e+00]]
